spring.application.name=mock-rest
openapi.mockIntegrationEndpoint.base-path=mock-rest
server.port=9091

spring.config.import=optional:errors.yaml

spring.datasource.url=jdbc:h2:mem:mockdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.sql.init.schema-locations=classpath:create_mock_table.sql
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console

### Logbook Configurations ###
logging.level.ROOT=INFO
logbook.format.style=http
logging.level.org.zalando.logbook=TRACE


error-service.default-error.http-status=500
error-service.default-error.error-code= "1"
error-service.default-error.error-message= "\u0421\u0435\u0440\u0432\u0438\u0441 \u0432\u0440\u0435\u043C\u0435\u043D\u043D\u043E \u043D\u0435\u0434\u043E\u0441\u0442\u0443\u043F\u0435\u043D"
